### ISSUE TITLE
golang.org/x/* packages problem

### ISSUE THREAD

**Issue by kpashka** [maxwellhealth/gofile-generator#2]
I'm using [golang.org/x/net/html](https://godoc.org/golang.org/x/net/html) package, just discovered, that your tool skips the package name for it.

**Comment by jraede** [comment]
Correct. My thinking was, after the domain (e.g. "github.com"), the first segment would be the account name and the second segment would be the package name. Seems like any of the "x" packages would have an issue. Is the actual git repo in the "x/net/html" folder? Or is it in "x/net"?

**Comment by kpashka** [comment]
@jraede I think the repo is in "/x/net/html". But if you look at list of packages in godoc [here](https://godoc.org/-/index), you can find longer and even shorter (e.g. https://godoc.org/upper.io/queue) combinations of import path parts.

I guess you just gotta modify your regexp to smth that should start with a domain name and end with anything.

**Comment by jraede** [comment]
So, I'm not sure this is an actual problem. I'm looking at the "/x/" packages (crypto, for example). The git repo is golang.org/x/crypto, but there is a subpackage inside of there (bcrypt) that you can include separately, but has no repo of its own. So, for the purposes of this tool, we want to get the commit hash of golang.org/x/crypto, because there's no commit hash for golang.org/x/crypto/bcrypt.

Seems like that would also apply to /x/net/html.
